In [143]:
import pandas as pd
import numpy as np
df = pd.read_csv('../data.csv')

In [144]:
df.head(1)

  text
0  你好吗

In [145]:
import jieba
df['cut'] = df['text'].apply(lambda x: [i for i in jieba.cut(x)]) #分词

In [146]:
corpus = []
for i in df['cut'].values:
    corpus += i

In [147]:
corpus = list(set(corpus)) #词表

词频（TF） = 某个词在文章中的出现次数

In [148]:
tf = np.zeros(((len(df)), len(corpus))) #row：每句话；col：每个词

for row, sentence in enumerate(df['cut']):
    for col, word in enumerate(corpus):
        tf[row][col] = sentence.count(word) #直接统计出现次数 未进行归一化

逆文档频率（IDF） = log（语料库的文档总数/包含该词的文档总数）

In [149]:
idf = np.zeros((len(corpus), len(df))) #实际上idf为len(corpus)维度，考虑到tfidf计算，将其进行broadcast

for row, word in enumerate(corpus):
    df_ = 0
    for col, sentence in enumerate(df['cut']):
        if word in sentence:
            df_ += 1
    idf[row] = np.log(len(df)/ df_)

In [150]:
tf_idf = tf * idf.T

In [151]:
tf_idf.shape

(9, 18)

In [152]:
pd.DataFrame(tf, columns=corpus)

     很    了   在家   今天    吗    在    我  ...   喜欢   你好    想    ，   请问    呀    去
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0  1.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2  0.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  2.0  1.0
5  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[9 rows x 18 columns]

In [153]:
pd.DataFrame(idf.T, columns=corpus)

          很         了        在家  ...        请问         呀         去
0  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
1  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
2  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
3  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
4  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
5  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
6  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
7  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213
8  0.954243  0.954243  0.954243  ...  0.954243  0.954243  0.653213

[9 rows x 18 columns]

In [154]:
pd.DataFrame(tf_idf, columns=corpus)

          很         了        在家  ...        请问         呀         去
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000  ...  0.954243  0.000000  0.000000
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.653213
4  0.000000  0.000000  0.000000  ...  0.000000  1.908485  0.653213
5  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
6  0.000000  0.954243  0.000000  ...  0.000000  0.000000  0.000000
7  0.000000  0.000000  0.954243  ...  0.000000  0.000000  0.000000
8  0.954243  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[9 rows x 18 columns]